### ISSUE TITLE
Soldiers can't spawn naturally or from spawn eggs

### ISSUE THREAD

**Issue by MrRedstoneA1** [Cubed-Development/Modern-Warfare-Cubed#103]
## Describe the bug

Even if soldier spawn rate is set to 1.0 they won't spawn. Spawn eggs fail to work. Only way to spawn them is through /spawn

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Set soldier spawn rate to 1.0
2. Try to find any by flying around for a bit
3. Try to spawn one from a spawn egg
4. Soldiers won't spawn

## Expected behavior

Soldiers should spawn naturally and from spawn eggs.

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

## Logs or/and crash reports

https://mclo.gs/j5voLVi

## Versions

- Modern Warfare Cubed: 0.1-dev-11
- Forge: 14.23.5.2860
- Java: 1.8.0_322 64bit
- Java JVM: Hotspot

## Specification:

- OS: Windows 11
- CPU: Ryzen 7 3700X
- GPU: Nvidia Geforce RTX 3070
- RAM Allocated: 8GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

When spawned with commands, they throw an error message.
(Note that minecraft did not actually crash here even though it output a crash report that I uploaded above)

**Comment by Koud-Wind** [comment]
I also noticed this issue when translating

**Comment by Paneedah** [comment]
Seems to be an equipment issue. Should be an easy fix in all fairness.

@SticksDeveloper could you please look into the issue?

**Comment by Koud-Wind** [comment]
> 好像是装备问题 公平地说，这应该是一个简单的解决方案。
> 
> @SticksDeveloper你能调查一下这个问题吗？

I noticed this issue from the dev8 version until I saw it https://github.com/Cubed-Development/Modern-Warfare-Cubed/commit/236609f6747912a4e6cacbb82852b35b9d47b61b , 
I changed terrorist to a different name (such as terrorist1), so when I try to generate terrorist, the error I get is the same as when I generate Soldier
