### ISSUE TITLE
Conflict with the InventoryHUD+ mode

### ISSUE THREAD

**Issue by SailorWang2004** [Cubed-Development/Modern-Warfare-Cubed#105]
(I am a player from China forgive me for my poor English and can only use translation software for reporting)
## Describe the bug

The mod link : https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge
--> 
InventoryHUD+ is a secondary module. It can display equipment, handhelds, etc. on the screen.
As soon as the player wears any MWC hat gear (including night vision devices, gas masks), these features disappear
but as long as the player is armed with an MWC guns, these functions are restored!

## Reproducibility
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

***Steps to reproduce the behavior:***

1. Bring any WMC hats
2. Do not hold any MWC guns

## Expected behavior

Wearing any MWC helmet will not affect the functionality of the InventoryHUD+ mod

## Screenshots or/and videos

In the picture, I am wearing a GPNVG-18 night vision device and holding an M4A1
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/90081974/f67398a1-afad-49c5-8b6d-79494cde72e8)

After that I switched to other items and the ability to show my equipment disappeared
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/90081974/dd326612-9ecc-464e-b5ff-f219850796c4)

When I took off the GPNVG-18 night vision device it was back to normal
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/90081974/7f919ba7-b26a-4357-9663-fd2e36f3d9ab)

## Logs or/and crash reports

https://mclo.gs/oJMQHkE

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-11
- Forge: 1.12.2 - 14.23.5.2860
- Java: jre 8 - 8.0.301
- Java JVM: Hotspot

## Specification:

- OS: Windows 10
- CPU: Inter i5 2500k
- GPU: GTX 950
- RAM Allocated: 16GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 3.30GHz Boost around 4.4Ghz
- CPU Core: 4 
- CPU Threads: 4
- RAM Size: 16GB
- RAM Speed: 1866MHz
- Storage Type: SSD
- GPU VRAM: 1GB

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by MrRedstoneA1** [comment]
this is pretty weird, I also use inventory hud+ but I can't replicate the issue. Possible mod incompatibility?

**Comment by SailorWang2004** [comment]
> 

Can you tell me your inventory HUD+ mod version?

**Comment by SailorWang2004** [comment]
> this is pretty weird, I also use inventory hud+ but I can't replicate the issue. Possible mod incompatibility?

Can you tell me your inventory HUD+ mod version ?

**Comment by Koud-Wind** [comment]
头盔有HUD, 只是被覆盖了, betterPVP也会这样

**Comment by MrRedstoneA1** [comment]
> > this is pretty weird, I also use inventory hud+ but I can't replicate the issue. Possible mod incompatibility?
> 
> Can you tell me your inventory HUD+ mod version ?

InventoryHUD-1.12.2.forge-3.4.4

**Comment by Desoroxxx** [comment]
Fixed in #106
