### ISSUE TITLE
ADS Issue

### ISSUE THREAD

**Issue by Paneedah** [Cubed-Development/Modern-Warfare-Cubed#112]
## Describe the bug

When using ADS, you are meant to hold down the right mouse button to keep the ADS. Seems like when you click the fire button and let go off of the RMB, it doesn't doesn't stop the ADS and you have to click it again.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Pickup any gun
2. Press and hold RMB
3. Press LMB
4. Let go off the RMB

## Expected behavior

Should stop the ADS and the player should stop aiming down the gun, just like without shooting.

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-12(Technically)

**Comment by Desoroxxx** [comment]
Fixed for 0.1
