### ISSUE TITLE
when i try to download mwcfrom here or from curse my pc blocks it cuz it has a virus or smt

### ISSUE THREAD

**Issue by THEBESTEVERRo** [Cubed-Development/Modern-Warfare-Cubed#124]
## Describe the bug

***A clear and concise description of what the bug is.***

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

## Expected behavior

***A clear and concise description of what you expected to happen.***

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

## Versions

- Modern Warfare Cubed: [e.g. MWC-0.1-Dev-1] 
- Forge: [e.g. 1.12.2 - 14.23.5.2860]
- Java: [e.g. JDK 8 - 352-b08]
- Java JVM: [e.g. Hotspot]

## Specification:

- OS: [e.g. Windows 10]
- CPU: [e.g. Ryzen 7 5800X]
- GPU: [e.g. Radeon RX 6500 XT]
- RAM Allocated: [e.g, 8GB]

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by SticksDeveloper** [comment]
just allow It, go to Windows security, and allow It I guess? I'm not sure how or why Windows is flagging the mod

**Comment by Desoroxxx** [comment]
bruh

**Comment by SticksDeveloper** [comment]
> bruh

_**certified windows moment**_
