### ISSUE TITLE
Translucent rendering layer of smoke is wrong

### ISSUE THREAD

**Issue by hfgm1145** [Cubed-Development/Modern-Warfare-Cubed#125]
## Describe the bug
There are someting wrong of smoke's translucent rendering layer.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [  ] I am unable to reproduce this issue consistently.

## To Reproduce
***Steps to reproduce the behavior:***

1.Throw a lot of M18 Smoke Grenades.
2.Set a translucent block.
3.Look at the translucent block through the smoke.

## Expected behavior

***A clear and concise description of what you expected to happen.***

Translucent blocks shouldn't be seen through the smoke

## Versions

- Modern Warfare Cubed: [e.g. MWC-0.1-Dev-11] 
- Forge: [e.g. 1.12.2 - 14.23.5.2859]
- Java： JDK 8 - 352-b08

_Sorry,i'm not very good at english._

**Comment by Desoroxxx** [comment]
Can't be fixed except if a miracle happens
