### ISSUE TITLE
Shaders dont work.

### ISSUE THREAD

**Issue by CrunchiBaguette** [Cubed-Development/Modern-Warfare-Cubed#131]
## Describe the bug
Im playing with optifine, when i lauch its fine, but as soon as i turn on shaders (whether its complemeteray or other it doesnt matter) the game freezes and eventually switches. afterward i relaunch the game and the shader seems to be applied, but when i launch the world the screen is stuck in the mincraft dirt texture phase, i can move and interact but its just a wall of dirt. . Im using the latest version of this mod found on curseforge and optifine 1.12.2 G5. Now this is where it gets even weirder, upon relaunching the game (because you cant play without seeing anything) if you dont change anything in the settings and try to launch your world, instead of dirt you'll see a white screen. However if you relaunch, change back to normal graphics, enter the world, your fine, exit, put shaders, reenter the world, then you'll once again see the dirt screen. Ive made a video you can check out. Video was too big so here is a link to youtube https://youtu.be/8z9fd33aI1U

***A clear and concise description of what the bug is.***

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [X ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Have the mod and optifine G5 1.12.2 (i have tried optifine F6 preview to no avail)
2. Launch the game
3. In Video Choose a shader of your liking, game freezes, eventually switches to shaders
4. Launch a world
5. dirt screen

## Expected behavior
Beautiful world with shaders

***A clear and concise description of what you expected to happen.***
I expect to see my minecraft world with the shaders appliede

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

## Versions

- Modern Warfare Cubed:[e.g. MWC-0.1-Dev-1
- Forge:  1.12.2 - 14.23.5.2859
- Java: 17.0.7" 2023-04-18 LTS
- Java JVM:  Hotspot

## Specification:

- OS: Windows 10
- CPU: Ryzen 5 3600
- GPU: RTX 3070 Ti
- RAM Allocated: 4GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by Desoroxxx** [comment]
Minecraft 1.12 currently cannot work with Java 17, I supposed that was just a mistake.

But please upload logs and debug logs with https://mclo.gs/

**Comment by CrunchiBaguette** [comment]
oh alright ill get Java 15 is that ok? Also here are logs https://mclo.gs/32IJy4B


> Minecraft 1.12 currently cannot work with Java 17, I supposed that was just a mistake.
> 
> But please upload logs and debug logs with https://mclo.gs/

**Comment by SticksDeveloper** [comment]
> oh alright ill get Java 15 is that ok? Also here are logs https://mclo.gs/32IJy4B
> 
> > Minecraft 1.12 currently cannot work with Java 17, I supposed that was just a mistake.
> > But please upload logs and debug logs with https://mclo.gs/
Minecraft 1.12.2 uses Java 8.

**Comment by CrunchiBaguette** [comment]
Yep i did a little bot of reaserch and now ive got java 8 still doesn't work though :( > > oh alright ill get Java 15 is that ok? Also here are logs https://mclo.gs/32IJy4B
> 
> > 
> 
> > > Minecraft 1.12 currently cannot work with Java 17, I supposed that was just a mistake.
> 
> > > But please upload logs and debug logs with https://mclo.gs/
> 
> 
> 
> Minecraft 1.12.2 uses Java 8.

**Comment by SticksDeveloper** [comment]
> Yep i did a little bot of reaserch and now ive got java 8 still doesn't work though :( > > oh alright ill get Java 15 is that ok? Also here are logs https://mclo.gs/32IJy4B
> 
> > > 
> > 
> > 
> > > > Minecraft 1.12 currently cannot work with Java 17, I supposed that was just a mistake.
> > 
> > 
> > > > But please upload logs and debug logs with https://mclo.gs/
> > 
> > 
> > Minecraft 1.12.2 uses Java 8.

anyways turn off MWC shaders.

STEPS:

In the main menu, there is a button It's called Mods hit that then search for "Modern Warfare Cubed"

then hit config after that hit rendering and then make sure everything is set to false, hit the screen shaders button at the bottom of the screen just above done and hit that make sure everything is false in there and you're good to go!
