### ISSUE TITLE
Crash problem with Tech guns mod

### ISSUE THREAD

**Issue by magianiam** [Cubed-Development/Modern-Warfare-Cubed#135]
Game version 1.12.2
Forge Version 14.23.5.2860

https://mclo.gs/wdjDE3j

Install MOD list
Modern-Warfare-Cubed-0.1-Dev-11.jar
techguns-1.12.2-2.0.2.0_pre3.2.jar

1　Open Weapon Workbench
2　Open the Crafting page
3　Click on the gun
4　Crash

 Specification:

- OS: Windows 11
- CPU: Core i7-12700KF
- GPU:RTX 3070
- RAM Allocated: 16G

**Comment by ralseilii** [comment]
sane issue will it be compatible with techguns-1.12.2-2.0.2.0_pre3.2.jar? i just need to lauch nuclear in the latest techgun version.by the way , the gui of mwc and techguns are overlapping together.

**Comment by Desoroxxx** [comment]
Fixed in MWC 0.1.4
