### ISSUE TITLE
Problems with Mobends

### ISSUE THREAD

**Issue by LittleKing2004** [Cubed-Development/Modern-Warfare-Cubed#136]
Mobends Mod version: 1.2.1-19.12.21

## Describe the bug

I looked at the previous iusse about Mobends. In the case of wearing MWC armor, the first-person grip will take effect. 
(Only shirt armor is useful)
I would like to ask, is it possible to fix it without wearing armor to work?
In addition, there is no aiming animation in third person

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## Expected behavior

First-person gun gripping animations do not require armor to take effect. 
The third person has aiming animations

## Screenshots or/and videos

The situation of not wearing armor in first-person view
![屏幕截图 2023-05-29 133911](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/90081974/b59a9a3f-43b2-4ec7-940c-8af103ce63c3)

In a third-person view, with or without armor. (I'm holding down the right mouse button to aim)
![屏幕截图 2023-05-29 133948](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/90081974/c957ba61-145c-4a7e-8e75-9f3a1e074f1a)

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-12
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK8
- Java JVM: Hotspot

**Comment by Paneedah** [comment]
All 3rd person animations have been removed by the Vic4Games team. This is planned to be re-added in the future.

**Comment by SticksDeveloper** [comment]
> All 3rd person animations have been removed by the Vic4Games team. This is planned to be re-added in the future.

no It's First person animations he's trying to say,
We do not have compatibility with mo bends sorry.
