### ISSUE TITLE
(Non-essential) Attachments.java future-proofing

### ISSUE THREAD

**Issue by TheDec0ded1** [Cubed-Development/Modern-Warfare-Cubed#139]
Attachments.java (and presumably the other weapon part files, though I haven’t tested them yet) will break via an ‘instruction code too large’ error if enough entries are added, meaning there’s a finite number of them that can be added at the moment. It’s easy to get the Attachments file to that point, it takes less than 50 new entries. 

For future-proofing’s sake, I’d recommend adding the ability to use additional files, example ‘Attachments2.java’ to add more possible entries. This is non-essential at the moment, but will be an issue in the future as content is added.

**Comment by Desoroxxx** [comment]
You don't need to use those files specifically and can you send console/logs of the `instruction code too large`, instruction too large only apply to methods, and you would need it to be 64KB of bytecode, that is an insane amount of bytecode, I doubt it is possible even with the current system.

**Comment by TheDec0ded1** [comment]
Looking over the logs, it's the now-unused CompatibleFmlPreInitializationEvent that did it, so I'm closing this issue.

**Comment by TheDec0ded1** [comment]
Replicated the issue *without* the compat layer, https://github.com/TheDec0ded1/Resounding-Modern-Warfare-Cubed/tree/active has it uploaded, the bug can be replicated by building it.

**Comment by Desoroxxx** [comment]
The problem isn't that the file is too large, the problem is that you are still using the compat layer even though it does not exist anymore.
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/82710983/d6b8c650-7cd5-4084-9ab4-444b49f5435e)

**Comment by Desoroxxx** [comment]
Anyway, why are you doing a Fork for unique sounds, just make a PR here for new unique sounds.

**Comment by TheDec0ded1** [comment]
Shoot, it's throwing an error during reobfjar for me, but that's not it. I'll double-check and make sure I got all the right files uploaded.

I'm running that fork as a personal project, and the new unique sounds aren't integrated, so it'd cause missing sounds if I were to PR it. The SFX work I do is my own copyrighted library, so I don't want to mix All Rights Reserved assets in an Apache licensed work.

**Comment by TheDec0ded1** [comment]
Forgot to upload three files, the aforementioned active branch should now be a perfect replica of what I'm seeing.

**Comment by Desoroxxx** [comment]
Will test again tomorrow
