### ISSUE TITLE
Selecting gun, crash game

### ISSUE THREAD

**Issue by Cor1t** [Cubed-Development/Modern-Warfare-Cubed#14]
## Describe the bug

When you select weapon, game crash.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

1. In mw.cfg set "enableAmmoCounter" to false
2. Create new world
3. Select weapon

## Screenshots or/and videos

https://streamable.com/3x2tmx

## Logs or/and crash reports
https://mclo.gs/HPRifwA

## Versions

- Modern Warfare Cubed: paneedah-modern-warfare-0.1-Dev-5
- Forge: 1.12.2 - 14.23.5.2859
- Java Version: 1.8.0_51, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

## Specification:

- OS:  Windows 10
- CPU: AMD ryzen 5 PRO 4650G
- GPU: NVIDIA GeForce RTX 3060 Ti
- RAM Allocated: 5GB

**Comment by Paneedah** [comment]
Going to look into this now.

**Comment by Paneedah** [comment]
Hi, I've noticed that you're running a serverely outdated version (about 300 versions behind) of Java which might be causing the issue.

Please update Java here: https://adoptium.net/en-gb/temurin/releases/?version=8

**Comment by JustDesoroxxx** [comment]
Please test this again after updating Java.

It appear you might be using the Curse Forge launcher if so follow these instruction to change the Java that Curse Forge launcher uses once newer Java installed https://youtu.be/EGUsEq6HOd0?t=25

**Comment by JustDesoroxxx** [comment]
Please test this again after updating Java.

It appear you might be using the Curse Forge launcher if so follow these instruction to change the Java that Curse Forge launcher uses once newer Java installed https://youtu.be/EGUsEq6HOd0?t=25

**Comment by Cor1t** [comment]
I did it and still the same

**Comment by JustDesoroxxx** [comment]
Can you show the CurseForge launcher Java page?

**Comment by Cor1t** [comment]
![image](https://user-images.githubusercontent.com/73612777/224370280-4eba30d1-20ff-42f4-a3b9-47fd0126d43a.png)

**Comment by Cor1t** [comment]
I can select destination of java.exe file

**Comment by JustDesoroxxx** [comment]
Weird, you might want to contact Curse Forge support

**Comment by Paneedah** [comment]
@Cor1t Any updates on this?

**Comment by Cor1t** [comment]
I can't change java version. I contacted to curseforge support and they said this option is for modloader, minecraft is using own java version. I tried to change that but when I selected java file, game doesn't start.

**Comment by Cor1t** [comment]
![image](https://user-images.githubusercontent.com/73612777/226723700-5efaf5b7-4e17-475c-8c72-c6cecc41a5c7.png)
Still the same error. (IDK what I did wrong)
![image](https://user-images.githubusercontent.com/73612777/226723947-e0e839a6-0a08-4d85-bf3d-99c2b399d74b.png)
![image](https://user-images.githubusercontent.com/73612777/226723972-8497d00f-2b80-4d2d-82e6-d849a5878ba4.png)

**Comment by Cor1t** [comment]
@Desoroxxx Try first fix door bug, because I think that could also solve this bug. Because when you restart game after door bug crash, selecting gun doesn't crash, but i'm using vanilla fix and game doen't restart on it's own, so then when I create new world selecting gun crashes game.

**Comment by Desoroxxx** [comment]
Oh wait, so this only happens when you crash and then Vanilla Fix gets you back to the main menu instead of quitting the game, and then you join a world back?

**Comment by Cor1t** [comment]
You can join the same world or make new one. The game will still crash.

**Comment by Desoroxxx** [comment]
But does this error happens without vanilla fix?

**Comment by Cor1t** [comment]
If I tested correctly, no. You need vanilla fix or mod which do the same job.

**Comment by Desoroxxx** [comment]
Okay so this is not an issue with MWC this is an issue with VanillaFix use CensoredASM instead, you can find a link to its Curse Forge page as well as all other useful optimization mods on Opticraft https://red-studio-ragnarok.github.io/Opticraft/
