### ISSUE TITLE
Custom Kill Messages 

### ISSUE THREAD

**Issue by strubium** [Cubed-Development/Modern-Warfare-Cubed#143]
## Is your feature request related to a problem? Please describe

No, but when players are shot, the only death message is <code>player</code> was pummeled by <code>player</code>

## Describe the solution you'd like
A custom kill message like
<code>player</code>was shot by <code>player</code> with <code>weapon</code>

## Describe alternatives you've considered
It's currently fine, but this would be nice. 

## Additional context
[Minecraft Wiki](https://minecraft.fandom.com/wiki/Death_messages#:~:text=was%20pummeled%20by%20%3C,projectiles%20do%20not%20deal%20damage.)

**Comment by Koud-Wind** [comment]
You can modify the name of the weapon to display it after the player kills the target. I have solved the problem of Throw killing the target and I am waiting for them to be merged

**Comment by Koud-Wind** [comment]
https://github.com/Cubed-Development/Modern-Warfare-Cubed/pull/141

**Comment by strubium** [comment]
Nice! I'll close this issue when it gets merged.

**Comment by Koud-Wind** [comment]
Not now, I can't directly modify it to the attack type of an arrow at the moment, there are some issues

**Comment by strubium** [comment]
Ah, ok.

**Comment by Paneedah** [comment]
This has been added into the Equipment Overhaul update.
