### ISSUE TITLE
Multiple magazines feed from the wrong bullet type

### ISSUE THREAD

**Issue by ValikLetsPlay** [Cubed-Development/Modern-Warfare-Cubed#150]
The "10rnd 7.62x54mm SVD magazine" is supposed to reload with 7.62x54mm bullets, but instead uses 7.62x39mm.
The "20rnd 6.5mm magazine" is supposed to reload with 6.5mm bullets, but instead uses 5.56x45mm.

## To Reproduce

1. Unload the appropriate mags, and see what bullets they give you.

## Expected behavior

You are supposed to be able to reload with the right bullets.

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-12
- Forge: 1.12.2 - 14.23.5.2859
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/113076005/8995d397-89d4-40ea-8261-00cc7c21a0da)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/113076005/c58e0cd2-ac49-415b-9265-d9fe099eeb58)

**Comment by Paneedah** [comment]
@Desoroxxx Issue resolved.
