### ISSUE TITLE
Integration with the Player Weight Mod

### ISSUE THREAD

**Issue by ValikLetsPlay** [Cubed-Development/Modern-Warfare-Cubed#155]
***A clear and concise description of what the problem is.*** 

I am using the Player Weight mod to add more realism and to limit the amount of items a player can carry. Unfortunately, the mod doesn't register the mwc slots such as vest and backpack, it doesn't count items inside of backpacks, and it does not count ammunition inside of magazines, and attachments on a gun. This basically removes most of the mod's purpose, because the player can stuff everything in a duffel bag and put it on their back, and the weight won't get picked up.

***A clear and concise description of what you want to happen.***

It would be REALLY awesome if you guys could manage adding the mentioned capabilities! I'll recap them here again just in case:
-backpack/vest slots are not registered, anything put in them won't count for weight
-anything inside a backpack does not get counted for weight, instead it's just the default backpack weight that's being counted.
-bullets inside of magazines are not counted, only the mag weight is counted
-attachments and mags on a gun are not counted, only the gun itself is counted

https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortType=1&search=Player%20Weight%20Mod

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/113076005/9d198215-fd0e-4a5c-a760-6369500ab63b)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/113076005/00c91b8f-c988-4975-9fdd-a3feec6bb814)

**Comment by strubium** [comment]
So if you do F3 + H you can see the advanced tooltips that show you the items name + any NBT tags. 

MWC stores data about the weapons in these NBT tags, so an empty mag would be <code>mwc:m4a1mag_2</code>and a full mag has the <code>ammo:30</code> NBT tag.

All you would need to do to edit the weight of mags that have an ammo NBT tag. 

This mod works great for seeing NBT tags: https://www.curseforge.com/minecraft/mc-mods/nbt-tooltip

**Comment by Desoroxxx** [comment]
We now use [Featurebase](https://modernwarfarecubed.featurebase.app/) for feature requests
