### ISSUE TITLE
Armor dupe with the backpack tab

### ISSUE THREAD

**Issue by boubouleuh** [Cubed-Development/Modern-Warfare-Cubed#156]
## Describe the bug

***A clear and concise description of what the bug is.***

We can dupe the helmet and the chestplate easily with spamming the backpack tab

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Put a backpack on
2. Remove the backpack
3. Spamclick the new tab
4. When the newtab have your helmet icon, return to your original inventory
5. Return to backpack inventory
6. Now you see the duped helmet and chestplate

## Expected behavior

The new tab is removed when you remove the backpack, No duped armors in the bag / bulletproof vest slot

## Screenshots or/and videos

[video](https://clipchamp.com/watch/EhNZgw7r4j1)

## Versions

- Modern Warfare Cubed: 0.1-Dev-12
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 (default curseforge one)

## Specification:

- OS: WIndows 11
- CPU: Ryzen 5 2600X
- GPU: Nvidia GTX 1060
- RAM Allocated: 10gb

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 3.60ghz boost around 4ghz
- CPU Core: 6
- CPU Threads: 12
- RAM Size: 32GB
- RAM Speed: 3200 MHz
- Storage Type: SSD
- GPU VRAM: 6GB

**Comment by Paneedah** [comment]
Issue has been fixed in 0.1-Dev-13. Please wait for the update.

**Comment by Desoroxxx** [comment]
> Issue has been fixed in 0.1-Dev-13. Please wait for the update.

?

**Comment by Paneedah** [comment]
Update: 0.1 release lol.
