### ISSUE TITLE
Players can customize the Inaccuracy of weapons.

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#16]
**Is your feature request related to a problem? Please describe.**
Players can customize the Inaccuracy of weapons.

**Describe the solution you'd like**
Players can customize the Inaccuracy of weapons in balancepacks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Config Overhaul](https://trello.com/c/e6vVkIpk/9-config-overhaul)

**Comment by Koud-Wind** [comment]
I have solved it myself, and after the merger, I will close this issue
