### ISSUE TITLE
Players can decide whether grenades can damage the map

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#17]
**Is your feature request related to a problem? Please describe.**
Explosive bullets and grenades always destroy the map.

**Describe the solution you'd like**
Players can determine whether explosive bullets and grenades can destroy blocks through the destroy GlassBlocks option

**Describe alternatives you've considered**
But when the world rule mobGriefing is closed, explosive bullets and grenades cannot destroy the map

**Additional context**
N/A

**Comment by JustDesoroxxx** [comment]
Will come in 0.1

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Config Overhaul](https://trello.com/c/e6vVkIpk/9-config-overhaul)

**Comment by Koud-Wind** [comment]
I have solved it myself, and after the merger, I will close this issue
