### ISSUE TITLE
Some weapons contain misalignment problems

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#18]
**Version:** [mw3.0-0.5.0.0]

**Describe the bug**
For me, I know some gun models or movement problems

**wrong**
1. The player's hand is not on the grip of P90 and origin12
![image](https://user-images.githubusercontent.com/123817318/220907168-940b313b-08df-4de5-90fd-d2efef7038ba.png)
![image](https://user-images.githubusercontent.com/123817318/220907220-7a208bd1-e644-4ef1-9566-e8e1eb91be7e.png)

2. Misalignment of accessories
![image](https://user-images.githubusercontent.com/123817318/220907575-06e95522-679c-4111-b56e-19559c08ca40.png)
![image](https://user-images.githubusercontent.com/123817318/220907750-b166a719-e94a-4b6a-a3dd-804bfa8715d5.png)
![image](https://user-images.githubusercontent.com/123817318/220907916-97f525a1-2f2f-4e23-98cc-74d58a654c41.png)
![image](https://user-images.githubusercontent.com/123817318/220907966-6585473d-9c4a-4dbd-a16c-b3a716e6fc22.png)
![image](https://user-images.githubusercontent.com/123817318/220909328-b9db48ce-021c-4e8d-9bf0-1dc9fe045991.png)
![image](https://user-images.githubusercontent.com/123817318/220912240-e43b6fc5-343e-43ba-95d6-fa4001cd7774.png)
![image](https://user-images.githubusercontent.com/123817318/220919535-95784807-d2c3-4137-90c3-5119afa037f9.png)

Mislocation of bullets from sniper rifle, This happens to almost every sniper rifle
![image](https://user-images.githubusercontent.com/123817318/220908058-3aa2ab76-927c-448d-a44f-88d68e25dff1.png)

3. About M134 smoke dislocation, fire dislocation
![image](https://user-images.githubusercontent.com/123817318/220909025-2994f8ab-5a2b-484f-88f7-179b75d587d2.png)

4. Some guns cannot be equipped with grips in adventure mode (mw:s7_10_tricun)

**Expected behavior**
Correct position

**Additional context**
https://github.com/Paneedah/paneedah-modern-warfare/issues/27
https://github.com/Paneedah/paneedah-modern-warfare/issues/67
https://github.com/Cubed-Development/Modern-Warfare-Cubed/issues/208

**Comment by Desoroxxx** [comment]
Will be redone better

**Comment by Koud-Wind** [comment]
> Will be redone better

For example what?

**Comment by Desoroxxx** [comment]
A giant report will be made with everything that needs to be fixed on weapons
