### ISSUE TITLE
Weapons shoot right compared to the aim

### ISSUE THREAD

**Issue by danmilko** [Cubed-Development/Modern-Warfare-Cubed#186]
## Describe the bug

Shooting is going in the right compared to the aim

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

1. Take any gun
2. Aim
3. Shoot
4. See where the bullets go

## Expected behavior

Bullets go right where aimed

## Screenshots or/and videos

https://drive.google.com/file/d/1YxVOzVygXzCEw7I1kIwrqPME-ZDGtney/view?usp=sharing

## Logs or/and crash reports

No crashing

## Versions

- Modern-Warfare-Cubed-0.1-Dev-12
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 - 351

## Specification:

- OS: Windows 10
- CPU: Ryzen 5 5600H
- GPU: GeForce RTX 3050 Laptop
- RAM Allocated: 8 GB

## Additional context
It doesn't matter what gun or scope do I use - the problem is still here. Removed all mods except OptiFine.

**Comment by danmilko** [comment]
But this is still hapenning for version on CurseForge or are you talking about some another version?

**Comment by danmilko** [comment]
> Already reported and is already fixed for 0.1

But this is still hapenning for version on CurseForge (0.1-Dev-12) or are you talking about some another version?

**Comment by Braiam23** [comment]
> > Already reported and is already fixed for 0.1
> 
> But this is still hapenning for version on CurseForge (0.1-Dev-12) or are you talking about some another version?

It refers to another version, the curseforge version is old

**Comment by danmilko** [comment]
> It refers to another version, the curseforge version is old

Ah, I see, thanks for the clarification!
