### ISSUE TITLE
Aiming is not as vivid as the previous version

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#20]
**Version:** [MWC-Dev-1~5]

**Describe the bug**
When aiming, the front sight will no longer follow the player's perspective slowly, And 100% speed follows the player's perspective, which may not be so vivid

**To Reproduce**
1. Right click weapon
2. Fast moving perspective

**Expected behavior**
Just like the previous version

**Screenshots / Videos**
https://streamable.com/of30js

**Additional context**
N/A

**Comment by Desoroxxx** [comment]
This seems to be intended as even Vic's 3.0 as it
