### ISSUE TITLE
Missing 3rd person animations for Proning

### ISSUE THREAD

**Issue by Paneedah** [Cubed-Development/Modern-Warfare-Cubed#202]
## Describe the bug

Quite self explanatory. We also can't still use the prone feature on Multiplayer servers.

**Note:** I'm aware that this issue is already widely known. I'm just putting it here to make sure it's remembered and recognized.

**Comment by Desoroxxx** [comment]
> We also can't still use the prone feature on Multiplayer servers.

Sadly even adding animations won't make it multiplier compatible due to the hitbox

**Comment by Desoroxxx** [comment]
Proning is removed in 0.2
