### ISSUE TITLE
Guns with missing sounds

### ISSUE THREAD

**Issue by Paneedah** [Cubed-Development/Modern-Warfare-Cubed#205]
## Describe the bug

List of guns that are missing reload sounds.

- [ ] M249
- [ ] M40A6
- [ ] MAS-21
- [ ] PP-91 Kedr
- [ ] SV-98
- [ ] APC9
- [ ] S7-10 Tricun
- [ ] Remington-700
- [ ] S&W .500 Magnum
- [ ] Chiappa Rhino
- [ ] Taurus Raging Hunter .44 Magnum
- [ ] Colt Python
- [ ] Colt M1911
- [ ] Browning Hi-Power
- [ ] MP-40
- [ ] M1928 Thompson
- [ ] Steyr AUG A1
- [ ] FN F2000
- [ ] StG-44
- [ ] G2 Contender
- [ ] M1 Carbine
- [ ] M712
- [ ] G42 Gewehr
- [ ] M1 Garand
- [ ] M124
- [ ] M202 FLASH
- [ ] RPG-7
- [ ] Uzi
- [ ] Saiga 12
- [ ] MP-43E
- [ ] HS-12
- [ ] Bren MKII
- [ ] M1941 Johnson (LMG)
- [ ] M1941 Johnson (Rifle)
- [ ] DP-28
- [ ] MG-34
- [ ] MG-42
- [ ] M60E4
- [ ] Stoner A1
- [ ] SSG-08
- [ ] DSR1
- [ ] L96A1
- [ ] M200 Intervention
- [ ] AS50
- [ ] GL-06
- [ ] M79 GL

### Credits for Report
Big thank you to discord user `voca_johnni` (AKA. `The Legendary John`) for compiling this list for us!

**Comment by Johnny9926** [comment]
Happy to be of service! ^^

**Comment by Desoroxxx** [comment]
List has no been kept updated but a lot of this is fixed in 0.2
