### ISSUE TITLE
Broken texture for some stuff when in hand (and in inventory)

### ISSUE THREAD

**Issue by thelegendaryjohn** [Cubed-Development/Modern-Warfare-Cubed#208]
### Here are some of the guns that are broken when in hand, plus images:
**- Chiappa Rhino:**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/d1a93f1d-711e-4ff6-aaeb-186ca0cd8b58)

**- FN F2000**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/e2aa5cfd-172e-4cdd-a070-c942ff3d4957)

**100rnd 5.56x45mm Stoner Magazine**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/66ab94a9-36be-43a8-85de-2b4ef50206bd)

**L96A1** (casing sticking out)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/967c1f59-0f5e-4aa7-b041-bb13565c8fdb)

**M200 Intervention** (casing sticking out)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/7a903f8b-d1de-47f4-a2de-193648f9dc53)

**S&W .500 Magnum**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/322a0d97-94dc-4163-b99e-7103806c50d4)

### These are some weapon parts and other stuff that looks broken in the inventory (and some in hand too):
**NOTE:** _I will always put them in my hotbar from left to right_
**- 25/50rnd .45 ACP Vector (Drum) Magazine**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/f687f27f-15d7-4c4d-bf2e-73714c2bd72a)

**- G11 K1/K2 Handguard**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/25e239d6-790c-476f-bb4b-9a217313bdc8)

**- SIG-556 Grip**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/f68fb61a-bf77-47da-b8e4-62c80dda95ef)

**- Vector Taped Grip**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/53639da4-e593-430e-8738-a70b91d3c7a3)

**- M249 (Upper) Handguard/Stock/Mil-Specs Stock/Para Stock/HK416 Stock**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/1881fd67-3420-43e5-9609-6c360be3080d)

**- item.mwc_FiveSevenSlide.name** (no proper name) (no texture)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/c727159a-100f-4acb-8099-771c82791237)

**- HK416 Receiver** (no texture)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/02c7efa8-12f4-441c-8155-92f34bc82b13)

**- item.mwc_C8SFWReceiver.name** (no proper name)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/84d2bb11-5213-45c8-877c-4b8eb8039a9c)

**- Leupold VX-6 CDS TMOA Rifle Scope**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/3f77d0ca-1cbb-47fe-ac45-0c05a41749bd)

**- Scorpion Rear/Front Iron Sight**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/795f80a9-852f-4c39-844f-a43c2b8df434)

**- item.mwc_oldiepinkcamo.name** (no proper name)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/424677ad-e0b7-4096-9942-dfb3471bbad7)
### Here are some guns that render the muzzle flash incorrectly:
**- Bren MKII**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/57a9f6fc-df19-4938-afd1-52842a8abebb)

**- M1941 Johnson (LMG)**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/689cb220-fba1-4ee5-a616-2ce4a912a54d)

**- M1941 Johnson (Rifle)**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/679fa7da-1cae-4fcd-889e-8842ceaf45d9)

**- DP-28**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/719e53d7-48a1-4e2a-8142-86ad742f1394)

**- MG-34**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/42d48b65-e2e8-4dc5-b6d4-1208a9d064f8)

**- MG-42**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/ff373384-2b70-41ca-bd49-63a1575650e6)

**- M60E4**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/23e9ce3d-324a-45a2-8434-ca3bea28df7d)

**- L96A1** (inside the barrel)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/7f4af5e1-9992-4e85-ba8c-4d8d4d5d948b)

**- M200 Intervention**
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/73589068/79e6a3eb-2682-488a-877f-c1ef810dbfb1)

#
**Versions:**
- Modern Warfare Cubed: MWC 0.1-Dev-14
- Forge: 1.12.2-14.23.5.2860
- Java: JDK 1.8.0_351-b10
- Java JVM: 25.351-b10 (64-bit)

**Specification:**
- OS: Windows 10 Enterprise
- CPU: Intel Core i7-2600U 3.40GHz
- GPU: NVIDIA Quadro K620
- RAM Allocated: approx. 10GB

**Comment by Desoroxxx** [comment]
There will be a big internal write up of all the weapon issue, a lot of theses have been fixed too
