### ISSUE TITLE
Weird shader lag

### ISSUE THREAD

**Issue by Burchard36** [Cubed-Development/Modern-Warfare-Cubed#220]
## Describe the bug

Pretty much the title, simply rendering a large gun like the AK-47 or M16A4 Cuts my FPS by about 30-40%, and rendering just 5-6 of the guns on screen result in almost 0 FPS, and, as the title suggest the same thing happens when looking at the NPC's from the mod

## Reproducibility

Seems that it may be an issue with AMD, I am on a 6700XT and with the graphics driver version 23.7.1

## To Reproduce

Drop a gun, or spawn a bandit on the ground

## Screenshots or/and videos

Here is the video from when i originally reported the issue in discord: https://discord.com/channels/801852948854079489/1128516203615354900/1131496795680284752

Do note, i have had the command `/wdb weapon liverender toggle` toggled the entire time (You can see it for a brief moment in the video)

## Logs or/and crash reports

Here is my logs: https://pastebin.com/LeMr3GKu (This happens without the modular suite of mods, gonna remove them i was just testing something)

## Versions

- Modern Warfare Cubed:0.1-Dev-14
- Forge: 1.12.2 - 14.23.5.2859 (I updated to 2860, same thing)
- Java:1.8.0_51 (Viewable in the video)
- Java JVM: Gonna be honest, have NO idea / Have any idea how to check this and I'm a java developer myself 🤣 

## Specification:

- OS: Windows 11
- CPU: Ryzen 5 7600x
- GPU: Radeon RX 6700xt
- RAM Allocated: 9GB

- CPU Speed: Overclocking enabled, Max boosts up to around 5.3ish Base is 4.7
- CPU Core: 6
- CPU Threads: 12
- RAM Size: 32GB
- RAM Speed: 4800MHz
- Storage Type:NVMe
- GPU VRAM: 12GB

## Additional context

I tried this with and without optifine, same results :)

**Comment by Koud-Wind** [comment]
Have you ever turned off world shaders and screen shaders?

**Comment by Burchard36** [comment]
> Have you ever turned off world shaders and screen shaders?

They were on the whole time, I just tried turning them off now and its pretty much the same result with the FPS

**Comment by Burchard36** [comment]
Okay, however though turning ever shader option off DOES fix the issue, ill ship my modpack with these off by default then 

Would this be an issue with AMD and there drivers, or some bug within MWCs shaders itself? I had this mod running a few months back on a rx570 8gb with a hefty overclock and TBH it held up pretty well (Never noticed/saw any frame drops when messing with guns and bandits), cant remember the driver version i was using though!

**Comment by Burchard36** [comment]
Okay, here is my final testing with the shaders setting: https://www.youtube.com/watch?v=bSDdntl6o9M

So, I can enabled EVERY shader, except that final top option, I can spam switch between stuff in my hotbar, render a gun and bandit on the screen without and major fps drops, however this seems to remove the skins feature from guns (seems it also messed up the drum texture too in the video I tried to restart the game with "Enabled All Shaders" to false and they stayed the same)

However, the moment I enable "Enable All Shaders" option it creates a horrid lag spike for every gun (And armor piece i assume too) rendered on the screen, but allows for the skins on guns to be rendered again

Disabling any of the other options other than "Enable All Shaders" really has no effect on performance, for me at least

**Comment by Desoroxxx** [comment]
Not an issue, the mod is just not very optimized in this current state, this will be something we will always work on, but it is not something we can just tick a box and "fix"
