### ISSUE TITLE
Tutorial custom recipe for workbench

### ISSUE THREAD

**Issue by javiburatos** [Cubed-Development/Modern-Warfare-Cubed#224]
Im trying to modify the recipes from workbench but i dont find any tutorial, my problem now is that i dont know all the options for CraftingGroup, Can anyone tell me this options please? Here i post my code.
 "entryName": "mwc:",
        "craftingGroup": "",
        "recipe": [
          {
            "entryName": "",
            "isOreDictionary": true,
            "count": 1
          }
        ]
      }

**Comment by javiburatos** [comment]
another question, in entry name is posible write a item with metadata like this --> mekanism:ore:4?

**Comment by Koud-Wind** [comment]
https://github.com/Paneedah/VMW-Balance-Packs/wiki/5.-Custom-Crafting-Recipes

**Comment by Desoroxxx** [comment]
Documentation will come after 0.1 don't expect everything to be there instantly though
