### ISSUE TITLE
Scope bug with Simpleores/SimplecoreAPI

### ISSUE THREAD

**Issue by eli67480** [Cubed-Development/Modern-Warfare-Cubed#226]
## Describe the bug

When loading MWC and Simpleores (and its dependency SimplecoreAPI), the scopes zoom out instead of zoom in. (see screenshots)

## To Reproduce

***Steps to reproduce the behavior:***

1. Create a Minecraft profile (I use forge-1.12.2-14.23.5.2859)
2. Place MWC 0.1-Dev.14 & redcore in the mod folder, run the game and try to aim with a scope
3. Do the same but this time add SimpleOres and SimpleCore API in your mod folder
4. Now the scopes zoom out instead of zoom in

## Versions

- Modern Warfare Cubed : [MWC-0.1-Dev-14] 
- SimpleOres : [1.12.2-1.11.2.2]
- SimpleCore API : [1.12.2-1.7.3.4]
- Forge : [1.12.2 - 14.23.5.2859]
- Java : [Java 8 1.8.0_333]

## Specification:

- OS : [Windows 10 Professional]
- CPU : [Intel Core 2 Quad CPU Q9550]
- GPU : [AMD Radeon HD 7800 Series]
- RAM Allocated : [8 Gb]

***Detailed Specs***

- CPU Speed : [2.83GHz overclocked at 3.00Ghz]
- CPU Core : [4 Cores]
- CPU Threads : [4 Threads]
- RAM Size : [8 Gb]
- RAM Speed : [800 Mhz overclocked at 1133 Mhz]
- Storage Type : [SSD]
- GPU VRAM : [1GB overclocked]
(Yes, this is an old computer but it's still running !)

## Screenshots:

Reference :
![2023-07-25_13 37 00](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/101655885/fb510a03-ea04-45e0-a7eb-b4d2b9099830)

Without SimpleOres & SimpleCore API :
![2023-07-25_13 39 32](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/101655885/4b20de5b-93f7-4966-9198-d57281482037)

With SimpleOres & SimpleCore API :
![2023-07-25_13 37 12](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/101655885/dcefe13e-635c-4a82-9548-786642328757)

**Comment by Desoroxxx** [comment]
> The issue has been resolved for 0.1 release.

No
