### ISSUE TITLE
Duplication Magazine

### ISSUE THREAD

**Issue by Creat789** [Cubed-Development/Modern-Warfare-Cubed#243]
If I reload a weapon with its magazine, the magazine stays in my inventory. So I unload my magazine which is in my weapon. Here I am with 2 chargers :)

[https://github.com/Cubed-Development/Modern-Warfare-Cubed/blob/master/src/main/java/com/paneedah/weaponlib/MagazineReloadAspect.java

**Comment by Paneedah** [comment]
Please follow the bug report template properly. We will not be reviewing this otherwise as you gave us little to no information.
