### ISSUE TITLE
minecraft 1.19.2

### ISSUE THREAD

**Issue by Chniper** [Cubed-Development/Modern-Warfare-Cubed#258]
hello, dear developers, I would really like to raise the mod version, that is, you would raise it to version 1.19.2, because minecraft is developing diligently due to recent events. 1.12.2 the old version is outdated. it's probably time to move on to a new stage. I really ask you to make a very cool mod for 1.19.2, and the theme is completely different. you can't include all the good mods for later versions of the game and the like in the build. I want you to relax and switch to rugby. Sir, I respect you and ask you to do this. you may have to rewrite the code. But I think it's worth it. we are a community of goodness. and I think it's possible. because your mod Modern Warfare is very cool, bro, and I wish your team good luck and may a revolution happen in minecraft. I really hope that you are reading this and listening to me and hope that you will respond. )))))

**Comment by Desoroxxx** [comment]
Seriously, I can't even imagine if that would happen in other games...

**hEy SiMs 3 mOdDeR yOu ShOuLd UpDaTe To SiMs 4**

Hey, at least I can have hope you are trolling

**Comment by Desoroxxx** [comment]
By the way, asking a modder if they can go on a specific version is the same level of dumb request as asking a Youtuber to do a collab with someone

**Comment by strubium** [comment]
> hello, dear developers, I would really like to raise the mod version, that is, you would raise it to version 1.19.2, because minecraft is developing diligently due to recent events. 1.12.2 the old version is outdated. it's probably time to move on to a new stage. I really ask you to make a very cool mod for 1.19.2, and the theme is completely different. you can't include all the good mods for later versions of the game and the like in the build. I want you to relax and switch to rugby. Sir, I respect you and ask you to do this. you may have to rewrite the code. But I think it's worth it. we are a community of goodness. and I think it's possible. because your mod Modern Warfare is very cool, bro, and I wish your team good luck and may a revolution happen in minecraft. I really hope that you are reading this and listening to me and hope that you will respond. )))))

Man fuck you, 1.12.2 is the stable modding version.

**Comment by Desoroxxx** [comment]
> Man fuck you, 1.12.2 is the stable modding version.

Please stay polite
