### ISSUE TITLE
Bug when rendering a "PipeLine" ?

### ISSUE THREAD

**Issue by Supertheobrg** [Cubed-Development/Modern-Warfare-Cubed#263]
***Steps to reproduce the behavior:***

1. join my server or solo
2. crash
3. it say error when rendering a render.bgl.PostProcessPipeline

## Screenshots or/and videos

https://medal.tv/games/minecraft/clips/1rhHHR-6TAINTw/d1337gpP7rBo?invite=cr-MSxVa1AsMTk3MTY0MDAzLA

## Logs or/and crash reports

https://mclo.gs/nJrXenh
https://mclo.gs/BA0rS58

## Versions

- Modern Warfare Cubed: [e.g. MWC-0.1-Dev-14] 
- Forge: [e.g. 1.12.2 - 14.23.5.2860]

## Specification:

NVIDIA Corporation' Version: '4.6.0 NVIDIA 536.23' Renderer: 'NVIDIA GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2
Win 10 

## Additional context

Sometime it crash and sometime it just go back to normal

**Comment by Desoroxxx** [comment]
Disable rain and snow effects in the config
