### ISSUE TITLE
Crash error with custom recipes with craftingmappings

### ISSUE THREAD

**Issue by javiburatos** [Cubed-Development/Modern-Warfare-Cubed#274]
## Describe the bug

My game crash when I try to modify the recipes for Ammo Press or weapon Workbench. More specifically, the crash take place when I turn to true the OreDictionary option. Other problem is that in the config the Metadata doesn´t work (below I post the config)

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

To obtein the crash i turn to true the OreDictionary option in craftingmapping file. Then, in the game when i select the item in workbench (or ammo press) whose recipe was modified, the game crash. For the problem with metadata only write a item with this, like in screenshots.
## Screenshots or/and videos
![1](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/60828897/7081f42b-4b77-40a3-96ac-7dca8a3ebd2e)
![2](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/60828897/ad452504-bfcd-432c-be7e-6fd74ff96de1)

## Logs or/and crash reports

https://mclo.gs/JfbsUt7

## Versions

- Modern Warfare Cubed: [MWC-0.1-Dev-14] 
- Forge: [e.g. 1.12.2 - 14.23.5.2860]

**Comment by Desoroxxx** [comment]
Craft mapping is getting removed in favor of a Groovy Script integration

**Comment by javiburatos** [comment]
So, can the weapon recipes be modified?

**Comment by Desoroxxx** [comment]
> So, can the weapon recipes be modified?

Yes it will with Groovy Script

**Comment by SticksDeveloper** [comment]
> So, can the weapon recipes be modified?

this was fixed anyways in dev-15, no idea why we're switching to groovy script

**Comment by Desoroxxx** [comment]
> this was fixed anyways in dev-15, no idea why we're switching to groovy script

1. Current system is a mess
2. Groovy Script allows actual scripting, which extends the functionality way past just changing the recipes, you can easily remove all recipes and then add your own, hell you could even use the workbench for every craft in your modpack if you so desire, you can also make it depend on game stage or a fancy research tree you made for your modpack, there is no limit
3. Groovy Script changes can be reloaded without restarting the game which makes it practical for any decently sized modpack
