### ISSUE TITLE
Armourer's Workshop Compatibility

### ISSUE THREAD

**Issue by EdoEquin0x** [Cubed-Development/Modern-Warfare-Cubed#275]
## Is your feature request related to a problem? Please describe

***A clear and concise description of what the problem is.*** 

I think it would be interesting to add compatibility with Armourers workshop. It's a mod that allows you to create custom weapons and armors models, and allowing customization on the weapons in this mod would be a great feature in my opinion!

## Describe the solution you'd like

***A clear and concise description of what you want to happen.***

Concretely, as shown during my tests. The 3D model is displayed correctly in 3rd person and the shooting animation, which is based on the vanilla bow animation (I think, correct me if I'm wrong) both work, the UI is also functional and only the rendering in first person is strange, I therefore propose to modify the 1rst person rendering to make it functional in first person (maybe by deactivating the first person animations of modern warfare? I don't know)

## Describe alternatives you've considered

***A clear and concise description of any alternative solutions or features you've considered.***

None, no gun mods except techguns are compatible with this mod and I really enjoy having the possibility to customize my weapons with some blocky hand-made models.

## Additional context

***Add any other context or screenshots about the feature request here.***
Link to the mod (He is open-sourced iirc): https://www.curseforge.com/minecraft/mc-mods/armourers-workshop
Link to some screen I took: https://imgur.com/a/t2cgpYr

**Comment by Desoroxxx** [comment]
We now use [Featurebase](https://modernwarfarecubed.featurebase.app/) for feature requests
