### ISSUE TITLE
crash with armor of  Dawn Of Time - Builder Edition mod

### ISSUE THREAD

**Issue by ralseilii** [Cubed-Development/Modern-Warfare-Cubed#278]
In the latest version of 1.12.2, when I wear armor from Dawn Of Time - Builder Edition , and try to hold a gun from modern warfare cubed, the game crashes.

**Comment by ralseilii** [comment]
when wearing chestplate from Dawn Of Time - Builder Edition and holding a mwc gun in first person view

**Comment by KorewaLidesu** [comment]
Can you send debug.log and crash log?

**Comment by Paneedah** [comment]
@ralseilii Could you follow the template and provide more information?

We need the crash report especially.

Thanks.
