### ISSUE TITLE
[Commit 0e93787]Gun shoot doesn't hit mob or make any damage.

### ISSUE THREAD

**Issue by 333mhz** [Cubed-Development/Modern-Warfare-Cubed#28]
## To Reproduce

1. Use oracle jdk8 361 build commit 0e93787 with vscode.
2. gradle forgegradle runclient with jei_1.12.2-4.15.0.268.
3. new game -> creative -> take a gun -> shoot.
4. See error: any gun shoot doesnt hit target mob or  make any damage.

I buid both commit 0e93787 and 0e6815d(tag:0.1-dev-7) and find this problem doesnt happen at commit 0e6815d(tag:0.1-dev-7) .
It seems:these two commit are the cause of this shoot-not-hit bug.
    563919a - Fixed some errors.
    8debf6c - A lot of code cleanup done for WeaponLib.  - Nowhere near done, but about 65 files into it!

## Expected behavior

Shoot the target, and make effective damage

## Screenshots or/and videos

none

## Logs or/and crash reports

none

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-1 - Commit 0e93787
- Forge: 1.12.2 - 14.23.5.2860
- Java: Oracle JDK 8 - 361
- Java JVM: Oracle hotspot

## Specification:

- OS:  Windows 10 22H2
- CPU: i7-1165g7
- GPU: Iris Xe
- RAM Allocated: 4GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 2.80GHz Boost around 5.00Ghz
- CPU Core: 4 (Attention Core not logical core)
- CPU Threads: 8 (Named Logical processors in task manager)
- RAM Size: 16GB
- RAM Speed: 4266MHz
- Storage Type: SSD
- GPU VRAM: 8GB (shared gpu memory)

**Comment by Desoroxxx** [comment]
Fixed as @Paneedah reverted this commit probably
