### ISSUE TITLE
Tactical animations

### ISSUE THREAD

**Issue by SfortzaPhantom** [Cubed-Development/Modern-Warfare-Cubed#29]
**Is your feature request related to a problem? Please describe.**
So there is a mod called Modular Movements, which adds several types of movement, like leaning or proning. This mod is heavily incompatible with Modern Warfare because of Modern Warfare's code principles. A big issue, if you'd ask me.

**Describe the solution you'd like**
I'd love to have leaning, sitting and proning animations in Modern Warfare. Or, at least, compatibility with Modular Movements.

**Describe alternatives you've considered**
Using Modular Warfare instead of Modern Warfare.

**Additional context**
none

**Comment by azuraerae** [comment]
Hello there, just a developer's opinion.
We've stated multiple times that the development of this mod will go through 3 stages; those stages being:
- Bug Fixing
- Feature Trimming 
- Actual Updates (New original features.)

At this point in time, we are only in the 1st phase and as such, the code will **massively** change. We have no idea of whether the code, when entirely fixed, will be incompatible with Modular Movements. 
So sadly we cannot respond to your request for the moment; please propose it later on when we'll get onto that 3rd phase. 

Thank you, 
- Azurae (Raeilgun)

**Comment by SfortzaPhantom** [comment]
Sure, just reposted it to this repo.

Actually waiting for total code rework :D

**Comment by azuraerae** [comment]
We don't know yet if it'll be a *full* rework, as we're still debating on whether we should redo the animation engine or not, but I promise you the mod will kick ass regardless 😁😁

**Comment by Desoroxxx** [comment]
We now use [Featurebase](https://modernwarfarecubed.featurebase.app/) for feature requests
