### ISSUE TITLE
Unable to craft guns or armor in workbench

### ISSUE THREAD

**Issue by MyUsernameisAstro** [Cubed-Development/Modern-Warfare-Cubed#331]
### Describe the bug

Whenever I attempt to craft guns or armor in the workbench, my nylon is used up but no gun or armor is created, the ammo press works fine. Running latest version of everything, no mods installed but optfine, MWC and Red Core, all latest version

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/107489039/aeb5f35e-a316-4773-a81f-c9310e42b98f

### Logs

https://mclo.gs/ktoxRoj

### MWC Version

0.1 Dev 16

### Forge Version

1.12.2 - 14.23.5.2589

### Red Core Version

0.6 Dev 1

### MixinBooter Version

8.9

### Java Version

1.8 - 251

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Paneedah** [comment]
We've identified the issue and a patch will be released on 0.1 Dev 17 in the very near future.

Thanks for reporting.

**Comment by Desoroxxx** [comment]
Our best team member is on it

**Comment by Paneedah** [comment]
@SticksDeveloper is 100% the best person for this issue.

**Comment by Desoroxxx** [comment]
And he totally not caused this issue

**Comment by Paneedah** [comment]
And he's clearly not broken it the 4th time now.
