### ISSUE TITLE
mob spawner with mwc:soldier without weapon

### ISSUE THREAD

**Issue by Charpyy** [Cubed-Development/Modern-Warfare-Cubed#333]
### Describe the bug

Using the mwcdev16 

When i use this command to make a mobspawner with soldier they spawn without weapon 
/setblock ~ ~-1 ~ mob_spawner 0 replace {SpawnCount:1,MaxNearbyEntities:2,SpawnRange:31,Delay:20,MinSpawnDelay:430,MaxSpawnDelay:1420,RequiredPlayerRange:50,SpawnData:{id:"mwc:soldier"}}

and idk if its true but a player from my server says that u cant hit them (sometimes)

**Important**
if u try to put soldier/terrorist egg on a non-modified mob spawner they spawn with weapon.

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/76815325/ebde26b4-b22c-49e1-bede-b9a6a531d6f6)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

no logs

### MWC Version

0.1 dev16

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

0.5 dev5

### MixinBooter Version

8.9

### Java Version

1.8 392

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Actually after reading in detail, this is normal behavior, you are spawning just a soldier, eggs contain the data for spawning a soldier with a weapon. 

However I am not familiar enough with Minecraft's commands to tell you how to create a spawner with a soldier with a weapon.

Maybe with the F3 menu and a spawner created via an egg, you could see the data that you need.
