### ISSUE TITLE
Backpack/Vest black-purple texture...

### ISSUE THREAD

**Issue by YassevZriona** [Cubed-Development/Modern-Warfare-Cubed#34]
## Describe the bug

Backpacks and vests textured being black-purple (null) textured
![Screenshot (609)](https://user-images.githubusercontent.com/95577745/226095983-835a53b2-64d5-4210-94cc-d695cd4aa622.png)

## Reproducibility

I have tried running the mod with just optifine since that is required, and the mod itself - yet the issue remains which means its a problem in the mod...

## To Reproduce

I don't think this is required

## Expected behavior

Backpacks and vests being rendered properly instead of black-purple (null) textures

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-7
- Forge: 1.12.2 - 14.23.5.2860
- Java: Java 8- 361
- Java JVM: Idk

## Specification:

- OS: Windows 10
- CPU: I3 1.9Ghz Dual Core
- GPU: Intregrated
- RAM Allocated: 8GB

**Comment by YassevZriona** [comment]
**I was banned in discord... reason and request for unban:**
I apologize about my disturbance, can I be pardoned for my mistakes?
I won't act rude again and will respect the fact that excessive pinging is punishable..
Can I be unbanned from modern warfare? I won't ever repeat my mistakes again.
My mistakes also include pinging vic4games, blaming him false after I misunderstood what Stick meant by it being hard to read "jim's" code... I thought vic was jim.. and Stick meant it was complex but really good thats why it was hard...
Im sorry I wont be rude like that every again

**Comment by Paneedah** [comment]
Please avoid using the GitHub for discord related situations.

**Comment by Paneedah** [comment]
This issue has already made it on our radar and seems to have occured when we changed Mod IDs from mw to mwc, we're going to investigate this issue further before the launch of 0.1.

**Comment by Desoroxxx** [comment]
Could you try again with the latest version, and close this if your issue has been fixed?

**Comment by SticksDeveloper** [comment]
Fixed this back in dev -  7
