### ISSUE TITLE
Crash with Linux

### ISSUE THREAD

**Issue by nobody444** [Cubed-Development/Modern-Warfare-Cubed#343]
### Describe the bug

The game crashes everytime on world loading/server joining with every modpack that includes VMW Cubed.
For some reason this is only happening on linux, I've tried to run it on windows and everything worked.
Mod reinstall doesn't work
I'm using Fedora 39 linux
Doesnt output any crash reports

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

doesnt output any crash report 

### MWC Version

0.1 Dev 15

### Forge Version

Last 1.12.2 forge version 

### Red Core Version

0.6 dev 1

### MixinBooter Version

8.9

### Java Version

1.8-392

### Java Virtual Machine

Hotspot

### Operating System

Fedora 39 (Linux)

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Please actually follow the template
