### ISSUE TITLE
Workbench does not keep track of the total ammount of items in it's inventory

### ISSUE THREAD

**Issue by MrRedstoneA1** [Cubed-Development/Modern-Warfare-Cubed#35]
## Describe the bug

For some reason, if you put nylon into two slots, crafting stops working. Say you have 64 nylon in slot 1 and you try putting more nylon into another slot. Now the craft button stops working. But if you take out the extra nylon, the craft button works again. I'll attach screenshots to better illustrate.

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. put some nylon into slot 1 of the weapons bench, then add other ingredients to craft an item.
2. Put more nylon into another slot.
3. Press craft
4. Nothing happens.

## Expected behavior

Having ingredients in more than one slot shouldn't stop crafting from working.

## Screenshots or/and videos

![Screenshot 2023-03-22 201529](https://user-images.githubusercontent.com/44941966/227003358-da0537e7-55b6-4f04-a486-8d0e9271e8c7.png)

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

## Versions

- Modern Warfare Cubed: 0.1-dev-7
- Forge: 14.23.5.2860
- Java: 1.8.0_322 64bit
- Java JVM: Hotspot

## Specification:

- OS: Windows 11
- CPU: AMD Ryzen 7 3700X 8-core
- GPU: Nvidia GEFORCE RTX 3070
- RAM Allocated: 8GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

Weirdly enough, issue seems to be only related to nylon, or the item in the first slot. If I try to replicate the issue with copper in the same fashion like this, I can still craft items:
![Screenshot 2023-03-22 201954](https://user-images.githubusercontent.com/44941966/227004297-f33819c9-66a4-4195-82c0-2894b3c789e8.png)

**Comment by MrRedstoneA1** [comment]
More info on the copper example: it seems to be related to the amount of items in that second slot vs. how many it takes to craft the item you want. If you put in one copper and attempt to craft a scope that requires two, the issue  happens. Same with the nylon, if there's less nylon in that slot than is required to craft the item, the issue happens.

**Comment by Paneedah** [comment]
@Desoroxxx patched.

**Comment by Paneedah** [comment]
Reference for additional commits relating to this issue: [684ac88](https://github.com/Cubed-Development/Modern-Warfare-Cubed/commit/eb5ab6c19e70cf64e8ab9a25f25eecc8d8b5786e)
