### ISSUE TITLE
Laser on gun breaks all shaders

### ISSUE THREAD

**Issue by MrRedstoneA1** [Cubed-Development/Modern-Warfare-Cubed#38]
## Describe the bug

Shaders work fine for the most part with only slight visual bugs here and there, but putting a laser on your gun completely breaks the shaders. I only tested a few shaders but they all had a seizure.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

1. Enable any shader. I used sildur's enhanced default.
2. Put a laser on your gun.
3. Turn the laser on.
4. Shader has a seizure.

## Expected behavior

Shader should work as before turning the laser on.

## Screenshots or/and videos

![image](https://user-images.githubusercontent.com/44941966/227962010-0a5d5947-2b79-4627-bb31-1231c65fa502.png)

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

## Versions

- Modern Warfare Cubed: 0.1-Dev-7
- Forge: 14.23.5.2860
- Java: JDK-8.0.322.6
- Java JVM: Hotspot

## Specification:

- OS: Windows 11
- CPU: AMD Ryzen 7 3700X
- GPU: Geforce RTX 3070
- RAM Allocated: 8GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

Edited to fix spelling error.

**Comment by SticksDeveloper** [comment]
VMW Shaders are not supported with other shaders. It is to be expected having issues as we cannot fix this only the shader Itself can fix that just disable the shaders for now
