### ISSUE TITLE
Guns/Grenades break when renamed with CraftTweaker

### ISSUE THREAD

**Issue by strubium** [Cubed-Development/Modern-Warfare-Cubed#385]
### Describe the bug

<mwc:m4a1>.displayName = "Super Awesome Gun"; causes the gun to be non-functional (Animations only play first frame, gun is not fireable) 

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

N/A

### Debug Logs

N/A

### MWC Version

 0.1.3

### Forge Version

1.12.2 - 14.23.5.2860/14.23.5.2859

### Red Core Version

0.5.1

### MixinBooter Version

9.1

### Java Version

1.8 - 392

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
We do not offer craft tweaker support, names of items in MWC should be changed with ressource pack since that is the way intended by Minecraft.

We do offer support for Groovy Script

**Comment by strubium** [comment]
> We do not offer craft tweaker support, names of items in MWC should be changed with ressource pack since that is the way intended by Minecraft.
> 
> We do offer support for Groovy Script

Cool
