### ISSUE TITLE
More built-in shader features

### ISSUE THREAD

**Issue by MrRedstoneA1** [Cubed-Development/Modern-Warfare-Cubed#39]
## Is your feature request related to a problem? Please describe

***A clear and concise description of what the problem is.*** 

Shaders are mostly incompatible with MWC since it has its own shaders. Even with all of those effects disabled, there are still problems or it just breaks shaders altogether, as I demonstrated in a bug report. There is no solution either, other than don't use shaders.

## Describe the solution you'd like

The only thing I really want is the wavy, realistic, reflective water. That's really it, just this one single effect that's in every shader pack. Maybe also reflective surfaces and shadows, but not necessarily. Adding built-in water shaders would solve this issue, at least for me. There should be no issues since it would be built into the mod's existing shaders.

> Remember that a great explanation leads to a greater understanding

## Describe alternatives you've considered

There really isn't an alternative, other than going back to vmw 2.0 or disabling shaders. Shaders just aren't compatible. I don't expect that full shader support would be possible either, since every shader is different and always changing and updating.

> Remember that a great explanation leads to a greater understanding

## Additional context

Well, this is what it looks like when the shaders break.
![image](https://user-images.githubusercontent.com/44941966/228017354-0c0f2dd7-f69c-4409-8499-c000e07c49d8.png)

**Comment by Desoroxxx** [comment]
You can disable MWC built in shaders to have shaders compatibility.

But the long term plan is to fix shaders compatiblity.
