### ISSUE TITLE
Incorrect building generation

### ISSUE THREAD

**Issue by fzrdwa123456** [Cubed-Development/Modern-Warfare-Cubed#394]
### Describe the bug

When used together with the "EFW: Forgotten Place" mod, it's unclear why buildings labeled with "MWC" are being generated

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

no logs

### MWC Version

0.1.3

### Forge Version

1.12.2 forge 14.23.5.2860

### Red Core Version

0.6 dev 3

### MixinBooter Version

9.1

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fzrdwa123456** [comment]
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/130232431/018c5809-4975-40c2-851a-d7139dec6fd9

**Comment by fzrdwa123456** [comment]
Mod link "https://www.curseforge.com/minecraft/mc-mods/efw-forgotten-place/comments"

**Comment by Desoroxxx** [comment]
We do not have building generation, you should report the issue to them
