### ISSUE TITLE
When aiming, the firearm will not automatically exit the aiming mode when reloading the magazine

### ISSUE THREAD

**Issue by fzrdwa123456** [Cubed-Development/Modern-Warfare-Cubed#411]
### Describe the bug

When aiming, the firearm will not automatically exit the aiming mode when reloading the magazine

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

no logs

### MWC Version

0.1.4

### Forge Version

1.12.2 forge 14.23.5.2860

### Red Core Version

0.6 dev 3

### MixinBooter Version

9.1

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fzrdwa123456** [comment]
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/130232431/46d69a15-c145-4949-b844-627fad2915c8

**Comment by fzrdwa123456** [comment]
Under normal conditions, aiming should not be possible. Even if I release the right mouse button, the aiming state will only be canceled when triggering a sprint or when the reloading is finished.

**Comment by Desoroxxx** [comment]
Intended in the future reloading will slow the player down a tiny bit
