### ISSUE TITLE
When cocking a sniper rifle, it does not automatically exit the aiming mode, and the field of view (FOV) is incorrect

### ISSUE THREAD

**Issue by fzrdwa123456** [Cubed-Development/Modern-Warfare-Cubed#412]
### Describe the bug

When cocking a sniper rifle, it does not automatically exit the aiming mode, and the field of view (FOV) is incorrect

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

no logs

### MWC Version

0.1.4

### Forge Version

1.12.2 forge 14.23.5.2860

### Red Core Version

0.6 dev 3

### MixinBooter Version

9.1

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fzrdwa123456** [comment]
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/130232431/cdae92e3-00c7-45ea-bc45-11080f3e0371

**Comment by fzrdwa123456** [comment]
The issue is similar to #411, but there's a difference. Although #411 fixed the FOV problem, the two issues related to aiming have not been resolved

**Comment by fzrdwa123456** [comment]
The issue is similar to #411, but with a key difference. While #411 has addressed the FOV problem, the two issues related to the aiming mode not automatically exiting have not been resolved

**Comment by Desoroxxx** [comment]
Pretty sure that was fixed
