### ISSUE TITLE
Game crash when selecting Tactical Night Vision goggles in Workbench

### ISSUE THREAD

**Issue by Infrizzy** [Cubed-Development/Modern-Warfare-Cubed#419]
### Describe the bug

The game crashes when selecting Tactical Night Vision goggles in the Weapons\Armor Workbench
The item can be equipped and rendered without issues if obtained through creative menu or similiar
The issue also occurs when dismantling the item, only at the end of the dismantle proces
The tests were done with MixinBooter 8,8 but the issue is also occurring with version 9.1

First crash, when selecting the item for assembly: 
https://mclo.gs/40ueABD - crash-2024-04-02_22.35.33-client

Second crash, when disassembling the item:
https://mclo.gs/6iFk8HC - crash-2024-04-02_22.41.51-server
https://mclo.gs/Xx30BKw - crash-2024-04-02_22.41.54-client

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/phrGc3p

### Crash Reports

https://mclo.gs/40ueABD - https://mclo.gs/6iFk8HC - https://mclo.gs/Xx30BKw

### MWC Version

0.1.5

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

1.7-1.12-0.5.1

### MixinBooter Version

8.8 - 9.1

### Java Version

 1.8.0_51

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PhilSkinn** [comment]
I am having the same issue. Forge version 14.23.5.2860, MWC version 0.1.6, 0.1.7, 0.2-dev. Seems to be in multiple versions. Java version 1.8.0_411.

**Comment by Desoroxxx** [comment]
Fixed in 0.1.8

- [Click here to see on CurseForge](https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed/files/5635141)
- [Click here to see on Modrinth](https://modrinth.com/mod/modern-warfare-cubed/version/0.1.8)
