### ISSUE TITLE
Floodlights not emitting light 

### ISSUE THREAD

**Issue by strubium** [Cubed-Development/Modern-Warfare-Cubed#43]
Self-explanatory, Towable Flood Light and Duel Flood Light don't emit light. Could be useful to have.

**Comment by Desoroxxx** [comment]
It's a prop

**Comment by strubium** [comment]
Yes, but a prop that can also emit light would be cool.

Idk why you added Won't Fix, this is a feature request, not a bug.

**Comment by Desoroxxx** [comment]
> Yes, but a prop that can also emit light would be cool.

If it has a function, it is not a prop

> Idk why you added Won't Fix, this is a feature request, not a bug.

They why aren't you using the feature request template?

**Comment by strubium** [comment]
> If it has a function, it is not a prop

Fine then, would you guys be ok with making it not a prop?

> They why aren't you using the feature request template?
 
I did not feel it was necessary to add the extra 3 paragraphs. I also felt that my one-sentence description worked in describing the cool thing I think should be added. 

(Also the enchantment label should show you that this is a "New feature or request")

**Comment by Desoroxxx** [comment]
> Fine then, would you guys be ok with making it not a prop?

Sure but not in the near term

> I did not feel it was necessary to add the extra 3 paragraphs. I also felt that my one-sentence description worked in describing the cool thing I think should be added.
> 
> (Also the enchantment label should show you that this is a "New feature or request")

I guess it's fine
