### ISSUE TITLE
Spams server log with warnings while holding magazines

### ISSUE THREAD

**Issue by Qmenator** [Cubed-Development/Modern-Warfare-Cubed#434]
### Describe the bug

Whenever I hold a magazine on my ubuntu multiplayer server, it spams the server log with: 
"[Server thread/WARN] [mwc] : Reconciling PlayerItemInstance: com.paneedah.weaponlib.PlayerMagazineInstance09cae2dda, but this method is empty"

Numbers and letters after "PlayerMagazineInstance" are seemingly random

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/TZe8naE

### MWC Version

0.1.5

### Forge Version

1.12.2 - 14.23.5.2680

### Red Core Version

0.5.1

### MixinBooter Version

9.1

### Java Version

1.8_362

### Java Virtual Machine

Hotspot

### Operating System

Ubuntu

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Fixed in 0.1.7
