### ISSUE TITLE
crash while loading a world

### ISSUE THREAD

**Issue by kklgtf** [Cubed-Development/Modern-Warfare-Cubed#443]
### Describe the bug

when a create or load a world the game load but when i click on the minecraft window the game crash

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/ALxse79

### MWC Version

0.1.6

### Forge Version

most recent one

### Red Core Version

0.6 dev 4

### MixinBooter Version

9.1

### Java Version

1.8.0_391

### Java Virtual Machine

Hotspot

### Operating System

windows 10

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kklgtf** [comment]
ok the log i put in the log above is giving the error of not enough allocated ram (it was 3250mb) i now allocated 8530mb but the game still crashes here is new log: https://mclo.gs/exuN23Z here is new debug log: https://mclo.gs/BbgX0VL the error code it gived was -1073741819

**Comment by Desoroxxx** [comment]
Outside of MWC controls, probably another mod, the log and debug logs sadly give no info,
