### ISSUE TITLE
Incessant Console Spam

### ISSUE THREAD

**Issue by BloxMaster3** [Cubed-Development/Modern-Warfare-Cubed#446]
### Describe the bug

everytime i run a server with MWC installed the console is spammed with:
`[23:33:39] [Server thread/WARN] [mwc]: Prepared state is null for PlayerItemInstance: m16a1[1607bd86-e5ad-48a9-81c4-cfdc074d8d7c]`
`[23:34:47] [Server thread/WARN] [mwc]: Prepared state is null for PlayerItemInstance: remington870[75b7bc08-ecbc-4ef4-a3cb-0e1e95ac50a6]`
`[23:39:19] [Server thread/WARN] [mwc]: Prepared state is null for PlayerItemInstance: m4a1[4e16157c-659f-4961-95fa-fd330c5b4bdf]`
it especially spams and even lags the server a bit when holding a magazine, as shown in the video in the Google Drive below, with things like: 
`[23:21:18] [Server thread/WARN] [mwc]: Reconciling PlayerItemInstance: com.paneedah.weaponlib.PlayerMagazineInstance@f3eddb89, but this method is empty`
but the code after @ varies wildly

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.

### Screenshots and/or videos

couldnt upload screenshot and video directly so heres GD: https://drive.google.com/drive/folders/1hkhSsDrXrQRZTIoK7GQPUAm50pEvkXyl?usp=sharing

### Logs

[Server Log](https://mclo.gs/LlBmeot) [Game Log](https://mclo.gs/9GYt18w)

### Debug Logs

[Server Log](https://mclo.gs/KQKqQu3) [Game Log](https://mclo.gs/bFxiHB2)

### Crash Reports

N/A

### MWC Version

1.12.2

### Forge Version

1.12.2-14.23.5.2860

### Red Core Version

Modern-Warfare-Cubed-0.1.6

### MixinBooter Version

9.1

### Java Version

jre-8.0.402.6

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by strubium** [comment]
Another way to reproduce: Open mwc's creative tab and scroll

**Comment by Desoroxxx** [comment]
Fixed in 0.1.7
