### ISSUE TITLE
Can't turn mob spawning off

### ISSUE THREAD

**Issue by MrRedstoneA1** [Cubed-Development/Modern-Warfare-Cubed#45]
## Describe the bug

Setting spawn value of each mob to 0.0 doesn't stop them from spawning.

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Go to config
2. Set spawn values of mobs to 0.0
3. Restart game to make sure changes take effect
4. Mobs are still able to spawn

## Expected behavior

Mobs should stop spawning when their respective spawn values are 0.0

## Versions

- Modern Warfare Cubed: 0.1-dev-8
- Forge: 14.23.5.2860
- Java: 1.8.0_322 64bit
- Java JVM: Hotspot

## Specification:

- OS: Windows 11
- CPU: AMD Ryzen 7 3700X
- GPU: Geforce RTX 3070
- RAM Allocated: 8GB

## Additional context

Only seems to apply to terrorists. I didn't run into any Tykes or zombies. Soldiers however are incapable of spawning at all, even from spawn eggs. If you try, the game seems to lock up. The whole game will lag apart from the player and chunks can't load.
You can use this command to quickly check if mobs actually spawn.
/testfor @e[type=mwc:terrorist]

**Comment by MrRedstoneA1** [comment]
seems to be solved now, I haven't seen any terrorists. Apparently all other mobs were removed at least temporarily?

**Comment by Paneedah** [comment]
Yes, we have removed the other mobs as part of the contagion removal. It was a lot of code that just messed with each other so it was super annoying.

They should be back at a later date!
