### ISSUE TITLE
Keep Press R cause crash

### ISSUE THREAD

**Issue by Frank-Wang-2007** [Cubed-Development/Modern-Warfare-Cubed#459]
### Describe the bug

Press R repeatedly quickly (just like booting into BIOS)  ( there was a Remington 700 in my hand ), the game would crash
(I'm using zulu vm

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/aE1Tusj

### MWC Version

0.1.7

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

1.7-0.5.1

### MixinBooter Version

9.1

### Java Version

1.8 - 402

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Adler-real** [comment]
+1 i have the same issue

**Comment by Desoroxxx** [comment]
Born to comment:
> Mhhh... fuck you

Forced to comment:
> Nice catch will hotfix!

For real though, nice catch, but, your poor R key... please be kind to your R key

**Comment by Desoroxxx** [comment]
Fixed in 0.1.8

- [Click here to see on CurseForge](https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed/files/5635141)
- [Click here to see on Modrinth](https://modrinth.com/mod/modern-warfare-cubed/version/0.1.8)
