### ISSUE TITLE
Glitch texture on bullet shell on ground

### ISSUE THREAD

**Issue by Renerosal01234** [Cubed-Development/Modern-Warfare-Cubed#468]
### Describe the bug

Am using Pojavlauncher but have glitch on bullet shell on ground can you add config to disable bullet shell

https://github.com/user-attachments/assets/b9146a1f-572d-40f3-b724-0c182bca4ce8

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

https://youtu.be/wd-kaxuyu6k?si=6m_pshmOZRNcimkt

### Logs

None

### Debug Logs

None

### Crash Reports

None

### MWC Version

Latest

### Forge Version

Latest 

### Red Core Version

Latest

### MixinBooter Version

Latest 

### Java Version

Latest 

### Java Virtual Machine

Hotspot

### Operating System

None

### GPU Vendor

Intel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Issue with your OpenGL emulator not MWC
