### ISSUE TITLE
Crouch Visual Bug

### ISSUE THREAD

**Issue by Deimos1054** [Cubed-Development/Modern-Warfare-Cubed#469]
### Describe the bug

The issue: When you go into Prone, your hitbox gets smaller, but your skin doesnt...

What is expected: The skin goes into a "crawl" mode...

I dunno, it does happen constantly to me, even when I only used the Main mod and its neccessary sub-mods... (Mixin and Red)

"put pic here, since i somehow cannot place it into Screenshots..."
![2024-07-31_22 44 46](https://github.com/user-attachments/assets/5b7fd98f-75ca-48a9-97ab-0eb40380fa55)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

Up above...

### Logs

https://mclo.gs/mu35e75

### Debug Logs

N/A

### Crash Reports

N/A (Didnt crash

### MWC Version

0.2-Dev-1

### Forge Version

1.12.2-14.23.5.2860

### Red Core Version

0.6-Dev-5

### MixinBooter Version

8.8

### Java Version

Version 8 Update 391 (Build 1.8.0_391-b13)

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

Intel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deimos1054** [comment]
PS: am using my sisters Laptop since we aren't at home (At home where I have my PC, we are elsewere...)

**Comment by SticksDeveloper** [comment]
Hey! this isn't a bug, we don't support this feature at the time, we do not have the animation for you crawling!, this feature will be removed in the future.
Solution: Use a movement mod that has crawling in it!
