### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SIXKL0V3** [Cubed-Development/Modern-Warfare-Cubed#472]
### Describe the bug

This error keeps popping up whenever I try to use MWC on my server, I originally thought it was my LAN connection or something to that effect but after buying a server and slowly putting in mods it eventually crashes, i've tried to remove and slowly put in mods again, and it will randomly give me this error.

![image_2024-08-12_190320039](https://github.com/user-attachments/assets/9ce2f044-c323-4da0-b8ea-aff57d29efeb)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/tVS9Aqa

### Crash Reports

https://mclo.gs/LP8GPoy

### MWC Version

0.2 Dev-1

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

0.6-Dev-7

### MixinBooter Version

9.2

### Java Version

1.8 - 392

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Fixed in 0.1.8

- [Click here to see on CurseForge](https://www.curseforge.com/minecraft/mc-mods/modern-warfare-cubed/files/5635141)
- [Click here to see on Modrinth](https://modrinth.com/mod/modern-warfare-cubed/version/0.1.8)
