### ISSUE TITLE
Bullet dismantle bug

### ISSUE THREAD

**Issue by CloudGFX** [Cubed-Development/Modern-Warfare-Cubed#480]
### Describe the bug

This bug also exists in VMW 3.0!
**It can be easily reproduced,just dismantle any bullets,1 bullet will be 6 coppers and 6 gunpowders with output.**

I found this problem may be there:
src/main/java/com/paneedah/weaponlib/crafting/ammopress/TileEntityAmmoPress.java
`public static final int BULLETS_CRAFTED_PER_PRESS = 6;`
If the value of it can be modified to 1,then this problem will be solved.
Or you can modify other code to figure out this bug.I think this bug will be a fatal problem to surival mode.Because we can produce the bullets free.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/

### MWC Version

0.18

### Forge Version

1.12.2 2860

### Red Core Version

0.5.1

### MixinBooter Version

9.3

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

Intel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Adaptive277** [comment]
this is the only problem that does not allow me to play with this mod in survival or add it to the assembly
