### ISSUE TITLE
NullPointerException in the method addCraftingInformationToTooltip

### ISSUE THREAD

**Issue by Andrey2211553** [Cubed-Development/Modern-Warfare-Cubed#488]
### Bug Report Summary for Developers:

The crash occurs while rendering the Ammo Press GUI in **Modern Warfare Cubed**. Specifically, it fails when trying to display crafting information tooltips for ammo press recipes. The issue is caused by a **`NullPointerException`** in the method `addCraftingInformationToTooltip` of `GUIContainerAmmoPress`.

### Details:
- **Error location**: 
  - `com.paneedah.weaponlib.crafting.ammopress.GUIContainerAmmoPress.addCraftingInformationToTooltip(GUIContainerAmmoPress.java:168)`
  - The error occurs when crafting tooltips are added to the GUI, causing a rendering failure.
  
- **Stacktrace Highlights**:
  - Error in: `GUIContainerAmmoPress.addCraftingInformationToTooltip()`
  - Method called during: `drawTooltips()` in `GUIContainerStation`
  - Resulting in: `NullPointerException` while rendering the ammo press screen.

### Affected Mods/Components:
1. **Modern Warfare Cubed (mwc: 0.1.8)**: The crash happens in its ammo crafting GUI logic.
2. **OptiFine**: It's active, which might alter rendering behavior but isn't necessarily the root cause.
3. **CoreMods**: Several mods affecting rendering and GUI handling are present, but `weaponlib` from **Modern Warfare Cubed** is the direct source of the error.

### Possible Causes:
- **Null Data in Tooltips**: The crash seems related to the crafting tooltip data being null or improperly initialized in the `addCraftingInformationToTooltip` method.
- **Mod Conflicts**: Potential conflicts with other mods (e.g., `MalisisCore`, `Techguns`, or OptiFine) might be affecting rendering or GUI handling.
- **OptiFine Interference**: While not directly mentioned in the error, OptiFine may interfere with GUI rendering and should be tested with and without it enabled.

### Steps to Reproduce:
1. Open the **Ammo Press GUI** in **Modern Warfare Cubed**.
2. Attempt to view or interact with crafting tooltips for any ammo press recipe.
3. The crash occurs when the tooltip should render.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/4kz7GFl

### MWC Version

0.1.8

### Forge Version

1.12.2

### Red Core Version

0.5.1

### MixinBooter Version

9.4

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Paneedah** [comment]
Did you ask ChatGPT to write this report for you? 🤔 This doesn't sound very human.

Regardless, I'm sure @Desoroxxx will look into this.

**Comment by Andrey2211553** [comment]
To some extent, yes, I used the chat gpt to correct my grammatical errors as well as it is all normally formalized. I wrote it all myself and I figured it out. I am a man from Ukraine and do not really know English.

**Comment by Andrey2211553** [comment]
And thank you so much for your response

**Comment by Desoroxxx** [comment]
Fixed in 0.1.9
