### ISSUE TITLE
Volvera la pronación algún dia?

### ISSUE THREAD

**Issue by AbrahamtheFenix2003** [Cubed-Development/Modern-Warfare-Cubed#65]
## Is your feature request related to a problem? Please describe

***A clear and concise description of what the problem is.*** 

Ex: I'm always frustrated when [...]

## Describe the solution you'd like

***A clear and concise description of what you want to happen.***

> Remember that a great explanation leads to a greater understanding

## Describe alternatives you've considered

***A clear and concise description of any alternative solutions or features you've considered.***

> Remember that a great explanation leads to a greater understanding

## Additional context

***Add any other context or screenshots about the feature request here.***

**Comment by AbrahamtheFenix2003** [comment]
desearia que vuelva la pronacion ya que no hay otro mod que haga lo mismo, solo e visto el de modular movements pero buguea muchas texturas de otros mods

**Comment by SticksDeveloper** [comment]
> 

Esta ya es una función planificada para volver a agregar la capacidad de rastrear
