### ISSUE TITLE
No event call for when a projectile breaks glass

### ISSUE THREAD

**Issue by BoomerSchmirtz** [Cubed-Development/Modern-Warfare-Cubed#67]
Hey!

When a glass is being broken by a projectile from a gun, no event is being called (BreakBlockEvent for example) so there's no way to catch that event. This prevents plugins that revert world damage from working.

**Comment by Desoroxxx** [comment]
Did it work in previous versions?

**Comment by BoomerSchmirtz** [comment]
Didn't mess with previous versions

**Comment by SticksDeveloper** [comment]
That's because there isn't a simple event for that,

Mods and Plugins are not supported by each other
turn off glass breaking in the config and you should be good.

**Comment by BoomerSchmirtz** [comment]
Would still love bullets to go through glass though, maybe just not break?

**Comment by SticksDeveloper** [comment]
> Would still love bullets to go through glass though, maybe just not break?

Kinda defeats the point

**Comment by BoomerSchmirtz** [comment]
True but otherwise there is no way to prevent glass breaking in safezones for example. You can't monitor the event

**Comment by SticksDeveloper** [comment]
> True but otherwise there is no way to prevent glass breaking in safezones for example. You can't monitor the event

You could just make a server-side mod to interfere with our If statement plugins may be easy they don't support mods

**Comment by Desoroxxx** [comment]
> True but otherwise there is no way to prevent glass breaking in safezones for example. You can't monitor the event

Best way to do this would just be to listen to the block break event and cancel it in safezone

**Comment by Paneedah** [comment]
> Best way to do this would just be to listen to the block break event and cancel it in safezone

@Desoroxxx His entire point is that it DOESN'T fire that event.

**Comment by Desoroxxx** [comment]
Then how does it breaks the block?

**Comment by Paneedah** [comment]
I'm pretty sure it's just a #setBlock()

**Comment by Desoroxxx** [comment]
After testing the event is successfully fired, either you are doing something wrong, or the software you are using is doing something wrong.
