### ISSUE TITLE
Issue with weapon bench only checking the first stack of a required item

### ISSUE THREAD

**Issue by Milosauce** [Cubed-Development/Modern-Warfare-Cubed#68]
i ran into a bug with the gun bench that seems easily patchable.
I was trying to craft combat boots that require 6 plastic plates and i had the plates in 1 stack of 64 and 1 stack of 5. It wouldn't let me craft it and I think it's because it was only checking the stack of 5 plates and assuming that i didn't have enough. Basically, i think the gun bench is only checking the first stack of a required item in the bench instead of all of the stacks.

**Comment by SticksDeveloper** [comment]
you gotta use the layout we have
