### ISSUE TITLE
Holster slot

### ISSUE THREAD

**Issue by Fallcrim** [Cubed-Development/Modern-Warfare-Cubed#70]
Hey, would'nt it be nice if we had an extra slot in the inventory (maybe in the MWC-Inv) where we can place a pistol of some sort to display it on our right leg. Maybe this could also work for bigger guns that would display on the back of the player!

**Comment by Desoroxxx** [comment]
We now use [Featurebase](https://modernwarfarecubed.featurebase.app/) for feature requests
