### ISSUE TITLE
Config translations are missing

### ISSUE THREAD

**Issue by shizotoaster** [Cubed-Development/Modern-Warfare-Cubed#81]
## Describe the bug

***A clear and concise description of what the bug is.***
Mod Config is missing some of it's translations even when en_us language used

## Reproducibility
- [x] I reproduced this issue with as few other mods as possible installed.

## To Reproduce

***Steps to reproduce the behavior:***

1. Run the game
2. Enter the config menu

## Screenshots or/and videos

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/51480483/0677b583-d435-49d5-8243-b7afa1e28842)

## Logs or/and crash reports
https://mclo.gs/j2e0Stc

## Versions

- Modern Warfare Cubed: 0.1-Dev-10
- Forge: 1.12.2 - 14.23.5.2860
- Java: 1.8.0-362
- Java JVM: openjdk

## Specification:

- OS: KDE Neon 5.27
- CPU: Ryzen 5 5600g
- GPU: Nvidia GeForce GTX 1050 2GB
- RAM Allocated: 4GB

**Comment by SticksDeveloper** [comment]
Will be fixed before or in 0.1

**Comment by Paneedah** [comment]
@SticksDeveloper claims he already fixed this for 0.1-Dev11
