### ISSUE TITLE
Returning to the explosion of VMW0.6 version

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#90]
## Is your feature request related to a problem? Please describe

For some server developers, they do not want the map to be damaged, so they have to disable explosion
At present, it seems that the damage caused by explosives cannot be modified, and flash bombs are still calling for explosions

## Describe the solution you'd like

I have a source code for the explosion class in VMW0.6 version here, I hope to be able to use it.

https://github.com/Cubed-Development/Modern-Warfare-Cubed/files/11454820/Explosion.zip

**Comment by Paneedah** [comment]
The old explosions are in basically no way different to the new explosions. The only difference is the config on strength (not sure if I ever added it yet).

Explosions work by using the World#createExplosion() method, which is standard Minecraft and should be catchable using the BlockExplodeEvent in Bukkit.
