### ISSUE TITLE
Incorrect bounding box for the workbench V2

### ISSUE THREAD

**Issue by Desoroxxx** [Cubed-Development/Modern-Warfare-Cubed#91]
## Describe the bug

The bounding bow of the workbench is too high; it should end at the table heigh.

And also, it is missing collision for the "wall" of the workbench.

## Additional context

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/82710983/4c051bd9-9a9c-4bf2-bb84-1bb5b8f8450d)

**Comment by Koud-Wind** [comment]
If the ammo press is placed on the workbench, players will suffer suffocation damage when approaching the ammo press

**Comment by SticksDeveloper** [comment]
> 

It's If you place double on top of eachother

**Comment by Desoroxxx** [comment]
> If the ammo press is placed on the workbench, players will suffer suffocation damage when approaching the ammo press

You shouldn't be able to place an ammo press on the workbench and that will be fixed this dev build

**Comment by Koud-Wind** [comment]
It should be like this: keep the player's head close to the amo_ Press, players will suffer suffocation damage

**Comment by Koud-Wind** [comment]
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/99187ff4-6157-4765-aef7-ae49d339ad5d)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/cc422bdf-ed48-4bb4-b04e-7cbe78050e24)

**Comment by Koud-Wind** [comment]
I think they are quite similar

**Comment by Desoroxxx** [comment]
Yes, but similar is not the same

**Comment by Desoroxxx** [comment]
And no they aren't one is an incorrect bouding box, and the otehr is the way TE are created in MWC is very wrong

**Comment by Paneedah** [comment]
Issue 91 will be fixed in dev-11

**Comment by Paneedah** [comment]
Re-Opened -- @SticksDeveloper We need the backboard fixed.
