### ISSUE TITLE
When the player's head approaches some MWC blocks, they will suffer suffocation damage

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#94]
## Describe the bug

For example: mw:ammo_press, mwc:ump45_gfl, mwc:scarecrow

## To Reproduce

1. 
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/ea483da3-9e4b-4012-923c-408b75624399)
2. Get close to it

**Comment by SticksDeveloper** [comment]
It's not a bug It's a feature >:)

**Comment by SticksDeveloper** [comment]
this is because the hitbox is setup in a special way will get fixed soon

**Comment by Desoroxxx** [comment]
> this is because the hitbox is setup in a special way will get fixed soon

Na this is because how fluffed up current TE are will be fixed TM
