### ISSUE TITLE
[Question] Stream: false meaning 

### ISSUE THREAD

**Issue by strubium** [Cubed-Development/Modern-Warfare-Cubed#95]
## Describe

in /src/main/resources/assets/mwc/sounds.json there is a "stream" modifier. What does it do?

Example
"nightvision_off": {
    "category": "master",
    "sounds": [
      {
       "name": "mwc:nightvision_off",
       "stream": false
      } 
    ]
  },

No sounds use "stream": true, so I'm confused as to its inclusion.

**Comment by Desoroxxx** [comment]
> stream: true/false. True if this sound should be streamed from its file. It is recommended that this is set to "true" for sounds that have a duration longer than a few seconds to avoid lag. Used for all sounds in the "music" and "record" categories (except Note Block sounds), as (almost) all the sounds that belong to those categories are over a minute long. Optional. If undefined, defaults to "false". Setting this to false allows many more instances of the sound to be ran at the same time while setting it to true only allows 4 instances (of that type) to be ran at the same time.

From: https://minecraft.fandom.com/wiki/Sounds.json

**Comment by Desoroxxx** [comment]
Also for questions please use our Discord

**Comment by strubium** [comment]
> stream: true/false. True if this sound should be streamed from its file. It is recommended that this is set to "true" for sounds that have a duration longer than a few seconds to avoid lag. Used for all sounds in the "music" and "record" categories (except Note Block sounds), as (almost) all the sounds that belong to those categories are over a minute long. Optional. If undefined, defaults to "false". Setting this to false allows many more instances of the sound to be ran at the same time while setting it to true only allows 4 instances (of that type) to be ran at the same time.

Well fuck, all I needed was to google it. Thank you!
